name: Local
values:
  - key: BASE_URL
    value: ''
  - key: ACCESS_TOKEN
    value: ''
  - key: REFRESH_TOKEN
    value: ''
  - key: ACCESS_TOKEN_USER_2
    value: ''
  - key: REFRESH_TOKEN_USER_2
    value: ''
