services:
  postgres:
    image: postgres:17-alpine
    container_name: indoors-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-indoors_db}
      POSTGRES_USER: ${POSTGRES_USER:-indoors_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-indoors_password}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: indoors-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
