# Generated by Django 6.0.5 on 2026-05-13 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ('-created_at',), 'verbose_name': 'Кот', 'verbose_name_plural': 'Коты'},
        ),
        migrations.AlterField(
            model_name='cat',
            name='fluffiness',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Пушистость'),
        ),
    ]
